#pragma once

namespace marble {
    enum DiagKind {
        // errors, warnings and notes
        ErrIntegerSuffixForFloatingPoint,
        ErrUnsupportedEscapeSequence,
        ErrCharLitLen,
        ErrExpectedExpr,
        ErrExpectedStmt,
        ErrExpectedToken,
        ErrExpectedId,
        ErrExpectedType,
        ErrUndeclaredVariable,
        ErrUndeclaredFuntion,
        ErrUndeclaredStructure,
        ErrUndeclaredTrait,
        ErrUndeclaredField,
        ErrUndeclaredMethod,
        ErrRedefinitionVar,
        ErrRedefinitionFun,
        ErrRedefinitionStruct,
        ErrRedefinitionField,
        ErrRedefinitionMethod,
        ErrRedefinitionTrait,
        ErrTypeMismatchNotNum,
        ErrTypeMismatchNotBool,
        ErrCannotCast,
        ErrUnsupportedTypeForOperator,
        ErrNotAllPathsReturnsValue,
        ErrFuntionCannotReturnValue,
        ErrMethodCannotReturnValue,
        ErrFewArgs,
        ErrAssignmentConst,
        ErrCannotBeHere,
        ErrCannotHaveAccessBeHere,
        ErrFieldInitialized,
        ErrAccessFromNonStruct,
        ErrFieldIsPrivate,
        ErrMethodIsPrivate,
        ErrCannotDeclareHere,
        ErrUndeclaredType,
        ErrMethodNotInTrait,
        ErrCannotImplTraitMethod_RetTypeMismatch,
        ErrCannotImplTraitMethod_FewArgs,
        ErrCannotImplTraitMethod_ArgTypeMismatch,
        ErrNotImplTraitMethod,
        ErrExpectedDeclarationInTrait,
        ErrDerefFromNonPtr,
        ErrDerefFromNil,
        ErrRefFromRVal,
    };
}
