#pragma once

namespace onyx {
    enum DiagKind {
        // errors, warnings and notes
        ErrIntegerSuffixForFloatingPoint,
        ErrUnsupportedEscapeSequence,
        ErrCharLitLen,
        ErrExpectedExpr,
        ErrExpectedStmt,
        ErrExpectedToken,
        ErrExpectedId,
        ErrExpectedType,
        ErrUndeclaredVariable,
        ErrUndeclaredFuntion,
        ErrUndeclaredStructure,
        ErrUndeclaredField,
        ErrUndeclaredMethod,
        ErrRedefinitionVar,
        ErrRedefinitionFun,
        ErrRedefinitionStruct,
        ErrRedefinitionField,
        ErrRedefinitionMethod,
        ErrTypeMismatchNotNum,
        ErrTypeMismatchNotBool,
        ErrCannotCast,
        ErrUnsupportedTypeForOperator,
        ErrNotAllPathsReturnsValue,
        ErrFuntionCannotReturnValue,
        ErrMethodCannotReturnValue,
        ErrFewArgs,
        ErrAssignmentConst,
        ErrCannotBeHere,
        ErrCannotHaveAccessBeHere,
        ErrFieldInitialized,
        ErrAccessFromNonStruct,
        ErrFieldIsPrivate,
        ErrMethodIsPrivate,
    };
}
